/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchBuilderRouteImport } from './routes/watch-builder'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PaymentRequiredRouteImport } from './routes/payment-required'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as FairnessRouteImport } from './routes/fairness'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrewRouteImport } from './routes/crew'
import { Route as CharterModeRouteImport } from './routes/charter-mode'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'

const WatchBuilderRoute = WatchBuilderRouteImport.update({
  id: '/watch-builder',
  path: '/watch-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRequiredRoute = PaymentRequiredRouteImport.update({
  id: '/payment-required',
  path: '/payment-required',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const FairnessRoute = FairnessRouteImport.update({
  id: '/fairness',
  path: '/fairness',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewRoute = CrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const CharterModeRoute = CharterModeRouteImport.update({
  id: '/charter-mode',
  path: '/charter-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/charter-mode': typeof CharterModeRoute
  '/crew': typeof CrewRoute
  '/dashboard': typeof DashboardRoute
  '/fairness': typeof FairnessRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/payment-required': typeof PaymentRequiredRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/watch-builder': typeof WatchBuilderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/charter-mode': typeof CharterModeRoute
  '/crew': typeof CrewRoute
  '/dashboard': typeof DashboardRoute
  '/fairness': typeof FairnessRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/payment-required': typeof PaymentRequiredRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/watch-builder': typeof WatchBuilderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/charter-mode': typeof CharterModeRoute
  '/crew': typeof CrewRoute
  '/dashboard': typeof DashboardRoute
  '/fairness': typeof FairnessRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/payment-required': typeof PaymentRequiredRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/watch-builder': typeof WatchBuilderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/charter-mode'
    | '/crew'
    | '/dashboard'
    | '/fairness'
    | '/leave'
    | '/login'
    | '/onboarding'
    | '/payment-required'
    | '/payment-success'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/watch-builder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/charter-mode'
    | '/crew'
    | '/dashboard'
    | '/fairness'
    | '/leave'
    | '/login'
    | '/onboarding'
    | '/payment-required'
    | '/payment-success'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/watch-builder'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/charter-mode'
    | '/crew'
    | '/dashboard'
    | '/fairness'
    | '/leave'
    | '/login'
    | '/onboarding'
    | '/payment-required'
    | '/payment-success'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/watch-builder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  CharterModeRoute: typeof CharterModeRoute
  CrewRoute: typeof CrewRoute
  DashboardRoute: typeof DashboardRoute
  FairnessRoute: typeof FairnessRoute
  LeaveRoute: typeof LeaveRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PaymentRequiredRoute: typeof PaymentRequiredRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  WatchBuilderRoute: typeof WatchBuilderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watch-builder': {
      id: '/watch-builder'
      path: '/watch-builder'
      fullPath: '/watch-builder'
      preLoaderRoute: typeof WatchBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-required': {
      id: '/payment-required'
      path: '/payment-required'
      fullPath: '/payment-required'
      preLoaderRoute: typeof PaymentRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fairness': {
      id: '/fairness'
      path: '/fairness'
      fullPath: '/fairness'
      preLoaderRoute: typeof FairnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew': {
      id: '/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof CrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charter-mode': {
      id: '/charter-mode'
      path: '/charter-mode'
      fullPath: '/charter-mode'
      preLoaderRoute: typeof CharterModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  CharterModeRoute: CharterModeRoute,
  CrewRoute: CrewRoute,
  DashboardRoute: DashboardRoute,
  FairnessRoute: FairnessRoute,
  LeaveRoute: LeaveRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PaymentRequiredRoute: PaymentRequiredRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  WatchBuilderRoute: WatchBuilderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
